variable "app_name" {}
variable "environment" {}
variable "region" {}
variable "lb_address" {}
variable "app_user_pool_client" {}
variable "app_user_pool_id" {}
variable "app_api_endpoint" {}
variable "site_files_dir" {}
variable "lambdaa_api_endpoint" {}